project/Board/Board/urls.py
from django.contrib import admin
from django.urls import path, include
from board_app import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('report/', include('report.urls')),
    path('notice/', include('notice.urls')),
    path('', include('board_app.urls')),
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    
    path('', views.index, name='index'),  # '/' 에 해당되는 path
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/Board/board_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('post', views.post, name='post'),
    path('post/<int:id>', views.detail, name='detail'),
    path('schedule', views.schedule, name='schedule'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/Board/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

project/Board/notice/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.notice, name='notice'),
    path('notice_post/', views.notice_post, name='notice_post'),
    path('<int:id>', views.notice_detail, name='notice_post_detail'),

  

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/Board/report/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.report, name='report'),
    path('report_post/', views.report_post, name='report_post'),
    path('<int:id>', views.report_detail, name='report_detail'),

  

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/Board/board_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Board(models.Model):
    author = models.CharField(max_length=10, null=False)
    title = models.CharField(max_length=100, null=False)
    content = models.TextField(null=False)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

class Schedule(models.Model):
    author = models.CharField(max_length=10, null=False)
    title = models.CharField(max_length=100, null=False)
    content = models.TextField(null=False)
    created_date = models.DateField()
    created_time = models.TimeField()

project/Board/common/models.py
from django.db import models

# Create your models here.

project/Board/notice/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Notice(models.Model):
    author = models.CharField(max_length=10, null=False)
    title = models.CharField(max_length=100, null=False)
    content = models.TextField(null=False)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

project/Board/report/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Report(models.Model):
    author = models.CharField(max_length=10, null=False)
    rank = models.CharField(max_length=10, null=False)
    title = models.CharField(max_length=100, null=False)
    content = models.TextField(null=False)
    content2 = models.TextField(null=False)
    content3 = models.TextField(null=False)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

project/Board/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    rank = forms.CharField(label="계급")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email", "rank")

project/Board/board_app/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse

from .models import *

# Create your views here.
def index(request):
    boards = {'boards': Board.objects.all()}
    return render(request, 'list.html', boards)

def post(request):
    if request.method == "POST":
        author = request.POST['author']
        title = request.POST['title']
        content = request.POST['content']
        board = Board(author=author, title=title, content=content)
        board.save()
        return HttpResponseRedirect(reverse('index'))
    else:
        return render(request, 'post.html')

def detail(request, id):
    try:
        board = Board.objects.get(pk=id)
    except Board.DoesNotExist:
        raise Http404("Does not exist!")
    return render(request, 'detail.html', {'board': board})

def schedule(request):
    if request.method == "POST":
        author = request.POST['author']
        title = request.POST['title']
        content = request.POST['content']
        created_date = request.POST['created_date']
        created_time = request.POST['created_time']
        board = Board(author=author, title=title, content=content, created_date=created_date, created_time=created_time)
        board.save()
        return HttpResponseRedirect(reverse('index'))
    else:
        return render(request, 'schedule.html')

project/Board/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

project/Board/notice/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse

from .models import *


def notice(request):
    notices = {'notices': Notice.objects.all()}
    return render(request, 'notice.html', notices)

def notice_post(request):
    if request.method == "POST":
        author = request.POST['author']
        title = request.POST['title']
        content = request.POST['content']
        notice = Notice(author=author, title=title, content=content)
        notice.save()
        return HttpResponseRedirect(reverse('notice'))
    else:
        return render(request, 'notice_post.html')

def notice_detail(request, id):
    try:
        notice = Notice.objects.get(pk=id)
    except Notice.DoesNotExist:
        raise Http404("Does not exist!")
    return render(request, 'notice_detail.html', {'notice': notice})

project/Board/report/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse

from .models import *


def report(request):
    reports = {'reports': Report.objects.all()}
    return render(request, 'report.html', reports)

def report_post(request):
    if request.method == "POST":
        author = request.POST['author']
        rank = request.POST['rank']
        title = request.POST['title']
        content = request.POST['content']
        content2 = request.POST['content2']
        content3 = request.POST['content3']
        report = Report(author=author, rank=rank, title=title, content=content, content2=content2, content3=content3)
        report.save()
        return HttpResponseRedirect(reverse('report'))
    else:
        return render(request, 'report_post.html')

def report_detail(request, id):
    try:
        report = Report.objects.get(pk=id)
    except Report.DoesNotExist:
        raise Http404("Does not exist!")
    return render(request, 'report_detail.html', {'report': report})

project/Board/templates/common/login.html
{% load static %}
{% block content %}
<div class="container my-3">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <div class="row my-3">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

project/Board/templates/common/signup.html
{% load static %}
{% block content %}
<div class="container my-3">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="rank">계급</label>
            <input type="text" class="form-control" name="rank" id="rank"
                   value="{{ form.rank.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

project/Board/templates/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판 - {{ board.title }}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm mb-3">
        <div class="container d-flex justify-content-between">
            <a href="/" class="navbar-brand d-flex align-items-center">
                <strong>게시판</strong>
            </a>
        </div>
    </div>
</header>
<div class="container">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ board.title }} - {{ board.author }}</h5>
            <p class="card-text"><small class="text-muted">{{ board.created_date | date:"Y-m-d h:i" }}</small></p>
            <p class="card-text">{{ board.content }}</p>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-auto mr-auto"></div>
        <div class="col-auto">
            <a class="btn btn-info" href="/post/edit/{{ board.id }}" role="button">수정</a>
        </div>
        <div class="col-auto">
            <form id="delete-form" action="/post/delete/{{ board.id }}" method="post">
                <input type="hidden" name="_method" value="delete"/>
                <button id="delete-btn" type="submit" class="btn btn-danger">삭제</button>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

project/Board/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

project/Board/templates/list.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판 - 목록</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="/"><strong>나만의 AI 부관</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarsExample04">
          <ul class="navbar-nav mr-auto">

              <a class="nav-link" href="notice/">공지사항 <span class="sr-only"></span></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="report/">실시사항</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="schedule">예정사항</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link disabled" href="">실시사항</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">예정사항</a>
            </li>
            {% endif %}       
          </ul>
        </div>
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{user.rank}} {{user.username}} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
      </nav>
    

{% if user.is_authenticated %}


{% else %}
{% block content %}
<div class="container my-3">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <div class="row my-3">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}
{% endif %}
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

project/Board/templates/notice.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판 - 목록</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="/"><strong>나만의 AI 부관</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarsExample04">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="">공지사항 <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="/report/">실시사항</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/schedule">예정사항</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link disabled" href="">실시사항</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">예정사항</a>
            </li>
            {% endif %}       
          </ul>
        </div>
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
      </nav>
    

{% if user.is_authenticated %}
<div class="container">
    <table class="table">
        <thead class="thead-light">
        <tr class="text-center">
            <th scope="col">#</th>
            <th scope="col">제목</th>
            <th scope="col">작성자</th>
            <th scope="col">작성일</th>
        </tr>
        </thead>
        <tbody>
        {% for notice in notices %}
        <tr class="text-center">
            <th scope="row">
                <span>{{ notice.id }}</span>
            </th>
            <td>
                <a href="/notice/{{ notice.id }}">
                    <span>{{ notice.title }}</span>
                </a>
            </td>
            <td>
                <span>{{ notice.author }}</span>
            </td>
            <td>
                <span>{{ notice.created_date | date:"Y-m-d h:i" }}</span>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if user.is_superuser %}
    <div class="row">
        <div class="col-auto mr-auto"></div>
        <div class="col-auto">
            <a class="btn btn-primary" href="notice_post/" role="button">글쓰기</a>
        </div>
    </div>
    {% endif %}
</div>
{% else %}
{% block content %}
<div class="container my-3">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <div class="row my-3">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}
{% endif %}
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

project/Board/templates/notice_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판 - {{ notice.title }}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm mb-3">
        <div class="container d-flex justify-content-between">
            <a href="/" class="navbar-brand d-flex align-items-center">
                <strong>게시판</strong>
            </a>
        </div>
    </div>
</header>
<div class="container">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ notice.title }} - {{ notice.author }}</h5>
            <p class="card-text"><small class="text-muted">{{ notice.created_date | date:"Y-m-d h:i" }}</small></p>
            <p class="card-text">{{ notice.content }}</p>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-auto mr-auto"></div>
        <div class="col-auto">
            <a class="btn btn-info" href="/post/edit/{{ notice.id }}" role="button">수정</a>
        </div>
        <div class="col-auto">
            <form id="delete-form" action="/post/delete/{{ notice.id }}" method="post">
                <input type="hidden" name="_method" value="delete"/>
                <button id="delete-btn" type="submit" class="btn btn-danger">삭제</button>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

project/Board/templates/report.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판 - 목록</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="/"><strong>나만의 AI 부관</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarsExample04">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/notice/">공지사항 <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="/report/">실시사항 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/schedule">예정사항</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link disabled" href="">실시사항</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">예정사항</a>
            </li>
            {% endif %}       
          </ul>
        </div>
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
      </nav>
    

{% if user.is_authenticated %}
<div class="container">
    <table class="table">
        <thead class="thead-light">
        <tr class="text-center">
            <th scope="col">#</th>
            <th scope="col">제목</th>
            <th scope="col">계급</th>
            <th scope="col">작성자</th>
            <th scope="col">작성일</th>
        </tr>
        </thead>
        <tbody>
        {% for report in reports %}
        <tr class="text-center">
            <th scope="row">
                <span>{{ report.id }}</span>
            </th>
            <td>
                <a href="/report/{{ report.id }}">
                    <span>{{ report.title }}</span>
                </a>
            </td>
            <td>
                <span>{{ report.rank }}</span>
            </td>
            <td>
                <span>{{ report.author }}</span>
            </td>
            <td>
                <span>{{ report.created_date | date:"Y-m-d h:i" }}</span>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="row">
        <div class="col-auto mr-auto"></div>
        <div class="col-auto">
            <a class="btn btn-primary" href="report_post/" role="button">글쓰기</a>
        </div>
    </div>

</div>
{% else %}
{% block content %}
<div class="container my-3">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <div class="row my-3">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}
{% endif %}
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

project/Board/templates/schedule.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판 - 목록</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="/"><strong>나만의 AI 부관</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarsExample04">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/notice/">공지사항 <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="/report/">실시사항</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/schedule">예정사항</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link disabled" href="">실시사항</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">예정사항</a>
            </li>
            {% endif %}       
          </ul>
        </div>
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
      </nav>



      
      <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">	
          
          <div class="container">
              <div class="row row-striped">
                  <div class="col-2 text-right">
                      <h1 class="display-4"><span class="badge badge-secondary">23</span></h1>
                      <h2>OCT</h2>
                  </div>
                  <div class="col-10">
                      <h3 class="text-uppercase"><strong>Ice Cream Social</strong></h3>
                      <ul class="list-inline">
                          <li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i> Monday</li>
                          <li class="list-inline-item"><i class="fa fa-clock-o" aria-hidden="true"></i> 12:30 PM - 2:00 PM</li>
                          <li class="list-inline-item"><i class="fa fa-location-arrow" aria-hidden="true"></i> Cafe</li>
                      </ul>
                      <p>Lorem ipsum dolsit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                  </div>
              </div>
              <div class="row row-striped">
                  <div class="col-2 text-right">
                      <h1 class="display-4"><span class="badge badge-secondary">27</span></h1>
                      <h2>OCT</h2>
                  </div>
                  <div class="col-10">
                      <h3 class="text-uppercase"><strong>Operations Meeting</strong></h3>
                      <ul class="list-inline">
                          <li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i> Friday</li>
                          <li class="list-inline-item"><i class="fa fa-clock-o" aria-hidden="true"></i> 2:30 PM - 4:00 PM</li>
                          <li class="list-inline-item"><i class="fa fa-location-arrow" aria-hidden="true"></i> Room 4019</li>
                      </ul>
                      <p>Lorem ipsum dolsit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                  </div>
              </div>
          </div>